// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pawel.Cms.External.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BookDTO
    {
        /// <summary>
        /// Initializes a new instance of the BookDTO class.
        /// </summary>
        public BookDTO()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BookDTO class.
        /// </summary>
        public BookDTO(int? id = default(int?), string title = default(string), string author = default(string))
        {
            Id = id;
            Title = title;
            Author = author;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "author")]
        public string Author { get; set; }

    }
}
